### ISSUE TITLE
Localisation des grilles du Metro (Erreur 404) --> changement vers 20 minutes ?

### ISSUE THREAD

**Issue by devwald** [benVigie/mots#32]
Bonjour,

Il semblerait que les grilles ne soient plus au même endroit.

Erreur dans les logs : 
```

Game started and waiting for players on port 1337
Express server listening on port 2121
	[ERROR]: Cannot retreive grid...
	[ERROR]: Wrong statusCode 404
[ERROR] Cannot retreive grid. Abort server.

[GRIDMANAGER] Try to load http://www.rci-jeux.com/ope/metro/mfleches/data/mfl2313.mfl

```
Pouvez vous remplacer la localisation des grilles ?

Par exemple pour 20 minutes : http://rcijeux.fr/drupal_game/20minutes/grids/180517.mfj

Merci d'avance.

Cdt.

**Comment by benVigie** [comment]
En effet, j'avais constaté ça récemment, il semble que Metro ne publie plus de grilles quotidienne. 

Deux façons de corriger ce problème:
  * Soit on charge les grilles de `20 minutes` comme tu le suggère. Cependant ça demande un peu de travail de mise en forme car les les grilles ne sont pas du meme format (j'avais déjà regardé à l'époque)
  * Soit pour un quick fix on peut charger la _grille de référence_ au lieu d'essayer de charger la _grille du jour_. Il semble que `rcijeux` conserve les précédentes grilles.

Dans un premier temps je vais mettre en place le quick fix. Cependant si vous voulez participer en intégrant les grilles de `20 minutes`, vos PR seront les bienvenues 😃  !

**Comment by benVigie** [comment]
C'est corrigé, maintenant le serveur chargera la grille `1125` par défaut, qui est toujours accessible.

Vous devez déjà le savoir, mais il existe 2 façons de changer de grille:
  * Au lancement du serveur en donnant le numéro de grille en paramètre `$ node server.js 4242`
  * En cours de jeu en tapant le numéro de la grille à charger dans le chat puis en cliquant sur `Grille`
